version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL...' &&
        until pg_isready -h postgres -p 5432; do sleep 1; done &&
        echo 'PostgreSQL ready. Running migrations...' &&
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
