[project]
name = "todo"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "alembic",
    "asyncpg",
    "pydantic-settings",
    "ruff",
    "psycopg2-binary"
]

[tool.ruff]
exclude = ["alembic/versions"]