"""Delete the todotssss

Revision ID: 2c7a0b1c76a7
Revises: 7fe03216c48c
Create Date: 2025-07-22 10:23:49.603455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7a0b1c76a7'
down_revision: Union[str, Sequence[str], None] = '7fe03216c48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todossss_id'), table_name='todossss')
    op.drop_table('todossss')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todossss',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('todo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], name=op.f('todossss_todo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('todossss_pkey'))
    )
    op.create_index(op.f('ix_todossss_id'), 'todossss', ['id'], unique=False)
    # ### end Alembic commands ###
