"""Deleting test table

Revision ID: 7fe03216c48c
Revises: 9fe26c86b8f8
Create Date: 2025-07-22 10:23:19.632941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe03216c48c'
down_revision: Union[str, Sequence[str], None] = '9fe26c86b8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_new_test_id'), table_name='new_test')
    op.drop_table('new_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('new_test_pkey'))
    )
    op.create_index(op.f('ix_new_test_id'), 'new_test', ['id'], unique=False)
    # ### end Alembic commands ###
