"""Adding new table

Revision ID: 9fe26c86b8f8
Revises: 2a9a2d3310c2
Create Date: 2025-07-22 10:22:09.352909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe26c86b8f8'
down_revision: Union[str, Sequence[str], None] = '2a9a2d3310c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_test_id'), 'new_test', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_new_test_id'), table_name='new_test')
    op.drop_table('new_test')
    # ### end Alembic commands ###
